In [1]:

import numpy as np
m = int(input("Enter the number of rows: "))
n = int(input("Enter the number of columns: "))
arr = np.random.randint(10,100,(m,n))

In [2]:

print("Original array:")
print(arr)
print("Shape of the array: ",arr.shape)
print("Type of the array: ",type(arr))
print("Data type of the array: ",arr.dtype)

Original array:
[[96 72 83]
 [85 40 80]
 [81 82 74]]
Shape of the array:  (3, 3)
Type of the array:  <class 'numpy.ndarray'>
Data type of the array:  int64


In [3]:
arr1 = arr.reshape(n,m)
print("Reshaped array:")
print(arr1)
print("Shape of the array: ",arr1.shape)
print("Type of the array: ",type(arr1))
print("Data type of the array: ",arr1.dtype)

Reshaped array:
[[96 72 83]
 [85 40 80]
 [81 82 74]]
Shape of the array:  (3, 3)
Type of the array:  <class 'numpy.ndarray'>
Data type of the array:  int64


In [4]:

arr2 = arr1.copy()
print("Copied array:")
print(arr2)
print("Shape of the array: ",arr2.shape)
print("Type of the array: ",type(arr2))
print("Data type of the array: ",arr2.dtype)

Copied array:
[[96 72 83]
 [85 40 80]
 [81 82 74]]
Shape of the array:  (3, 3)
Type of the array:  <class 'numpy.ndarray'>
Data type of the array:  int64


In [5]:

arr2[[0,1]] = arr2[[1,0]]
print("Swapped array:")
print(arr2)
print("Shape of the array: ",arr2.shape)
print("Type of the array: ",type(arr2))
print("Data type of the array: ",arr2.dtype)

Swapped array:
[[85 40 80]
 [96 72 83]
 [81 82 74]]
Shape of the array:  (3, 3)
Type of the array:  <class 'numpy.ndarray'>
Data type of the array:  int64


In [6]:

arr3 = arr2.copy()
print("Copied array:")
print(arr3)
print("Shape of the array: ",arr3.shape)
print("Type of the array: ",type(arr3))
print("Data type of the array: ",arr3.dtype)

Copied array:
[[85 40 80]
 [96 72 83]
 [81 82 74]]
Shape of the array:  (3, 3)
Type of the array:  <class 'numpy.ndarray'>
Data type of the array:  int64


In [7]:

arr3[:,0] = arr3[::-1,0]
print("Reversed column array:")
print(arr3)
print("Shape of the array: ",arr3.shape)
print("Type of the array: ",type(arr3))
print("Data type of the array: ",arr3.dtype)


Reversed column array:
[[81 40 80]
 [96 72 83]
 [85 82 74]]
Shape of the array:  (3, 3)
Type of the array:  <class 'numpy.ndarray'>
Data type of the array:  int64
