In [1]:
import numpy as np
arr = np.array([1,2,0,0,4,0])
print("Original array:")
print(arr)

Original array:
[1 2 0 0 4 0]


In [2]:

print("Test whether the elements of the said array are zero or not:")
print(np.isin(arr,0))
print("Test whether the elements of the said array are non-zero or not:")
print(np.nonzero(arr))
print("Test whether the elements of the said array are NaN or not:")
print(np.isnan(arr))

Test whether the elements of the said array are zero or not:
[False False  True  True False  True]
Test whether the elements of the said array are non-zero or not:
(array([0, 1, 4]),)
Test whether the elements of the said array are NaN or not:
[False False False False False False]


In [3]:
print("Indices of non-zero elements of the said array:")
print(np.nonzero(arr)[0])
print("Indices of zero elements of the said array:")
print(np.nonzero(arr==0)[0])
print("Indices of NaN elements of the said array:")
print(np.nonzero(arr!=arr)[0])

Indices of non-zero elements of the said array:
[0 1 4]
Indices of zero elements of the said array:
[2 3 5]
Indices of NaN elements of the said array:
[]
