In [1]:
import numpy as np
arr = np.random.rand(4,4)

In [2]:
print("Original array:")
print(arr)

Original array:
[[0.10537584 0.22212124 0.15700531 0.4602863 ]
 [0.50353771 0.03169854 0.13928517 0.66194737]
 [0.51018266 0.30854466 0.74824986 0.97740671]
 [0.46033461 0.62955231 0.74623917 0.36022978]]


In [3]:
print("Size: ",arr.size)
print("Memory size of one array element in bytes: ",arr.itemsize)
print("Memory size of the array in bytes: ",arr.size*arr.itemsize)

Size:  16
Memory size of one array element in bytes:  8
Memory size of the array in bytes:  128
