In [1]:

import numpy as np
m = int(input("Enter the number of rows: "))
n = int(input("Enter the number of columns: "))
arr = np.random.randint(1,10,(m,n))

In [2]:
print("Original array:")
print(arr)

Original array:
[[3 5 8]
 [5 6 9]
 [7 9 4]]


In [3]:

print("Shape of the array: ",arr.shape)
print("Type of the array: ",type(arr))
print("Data type of the array: ",arr.dtype)

Shape of the array:  (3, 3)
Type of the array:  <class 'numpy.ndarray'>
Data type of the array:  int64


In [4]:
arr1 = arr.reshape(n,m)
print("Reshaped array:")
print(arr1)

Reshaped array:
[[3 5 8]
 [5 6 9]
 [7 9 4]]


In [5]:

print("Shape of the array: ",arr1.shape)
print("Type of the array: ",type(arr1))
print("Data type of the array: ",arr1.dtype)

Shape of the array:  (3, 3)
Type of the array:  <class 'numpy.ndarray'>
Data type of the array:  int64
