In [1]:
import numpy as np
arr1 = np.random.rand(4,4)

In [2]:

print("Original array:")
print(arr1)

Original array:
[[0.76524671 0.09815293 0.91904398 0.8683925 ]
 [0.09312158 0.64310218 0.17523791 0.91182242]
 [0.04940907 0.81049715 0.27948297 0.86790502]
 [0.37173365 0.93003802 0.84526993 0.57292217]]


In [3]:
n = np.mean(arr1, axis=1)
n1 = np.std(arr1, axis=1)
n2 = np.var(arr1, axis=1)

In [4]:
print("\nMean: ",n)
print("\nstd: ",n1)
print("\nvariance: ",n2)


Mean:  [0.66270903 0.45582102 0.50182355 0.67999094]

std:  [0.33062474 0.33663381 0.34763818 0.22154399]

variance:  [0.10931272 0.11332232 0.12085231 0.04908174]
