In [6]:
import numpy as np
arr1 = np.random.rand(4,4)
arr2 = np.random.rand(4,4)
arr3 = np.random.rand(4,4)

In [8]:
print("Original array1:")
print(arr1)
print("Original array2:")
print(arr2)
print("Original array3:")
print(arr3)

Original array1:
[[0.67788076 0.10270292 0.25718889 0.66326641]
 [0.33819457 0.70556397 0.46953388 0.41915066]
 [0.50699546 0.62549487 0.18647615 0.41662369]
 [0.95518254 0.81701572 0.70761694 0.3327776 ]]
Original array2:
[[0.33647297 0.42268558 0.62034779 0.02113645]
 [0.63140987 0.54475318 0.74344792 0.74291683]
 [0.86940197 0.33376548 0.73702887 0.45489339]
 [0.3812809  0.9465817  0.83909009 0.96574352]]
Original array3:
[[0.65145055 0.88905992 0.99246154 0.58331006]
 [0.5411695  0.05087628 0.14633575 0.14372141]
 [0.65046157 0.83972631 0.74782059 0.96565331]
 [0.09032595 0.67115183 0.18548422 0.9973747 ]]


In [9]:
arr4 = arr3-arr2
print("Array4:")
print(arr4)

Array4:
[[ 0.31497758  0.46637434  0.37211375  0.56217361]
 [-0.09024037 -0.4938769  -0.59711217 -0.59919542]
 [-0.2189404   0.50596083  0.01079172  0.51075993]
 [-0.29095495 -0.27542987 -0.65360586  0.03163117]]


In [10]:
arr5 = arr1*2
print("Array5:")
print(arr5)

Array5:
[[1.35576152 0.20540584 0.51437778 1.32653282]
 [0.67638913 1.41112794 0.93906777 0.83830132]
 [1.01399092 1.25098973 0.37295229 0.83324738]
 [1.91036508 1.63403143 1.41523388 0.66555519]]


In [12]:

print("Covariance of Array1 and Array4:")
print(np.cov(arr1,arr4))
print("Correlation of Array1 and Array5:")
print(np.corrcoef(arr1,arr5))


Covariance of Array1 and Array4:
[[ 8.42517569e-02 -4.04345769e-02 -1.95397389e-03 -2.06537703e-02
   1.32439512e-04  3.14171332e-02 -3.29198571e-02  4.42403260e-02]
 [-4.04345769e-02  2.49204531e-02  1.21641382e-02  4.14486890e-03
   5.69742579e-03 -1.67852251e-02  3.71552788e-02 -4.08512375e-03]
 [-1.95397389e-03  1.21641382e-02  3.45228578e-02  1.51773212e-02
   3.53349180e-03  1.89556203e-02  2.31479196e-02  2.90432842e-02]
 [-2.06537703e-02  4.14486890e-03  1.51773212e-02  7.12271582e-02
  -2.46865476e-02  4.67586063e-02 -6.22300777e-02 -3.97764026e-02]
 [ 1.32439512e-04  5.69742579e-03  3.53349180e-03 -2.46865476e-02
   1.17897257e-02 -1.80530007e-02  3.71176089e-02  2.13892784e-02]
 [ 3.14171332e-02 -1.67852251e-02  1.89556203e-02  4.67586063e-02
  -1.80530007e-02  5.83858792e-02 -6.09045074e-02  1.55362984e-03]
 [-3.29198571e-02  3.71552788e-02  2.31479196e-02 -6.22300777e-02
   3.71176089e-02 -6.09045074e-02  1.33825407e-01  5.78886834e-02]
 [ 4.42403260e-02 -4.08512375e-03  2